export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  DUPLICATE_RESOURCE = 'DUPLICATE_RESOURCE',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  INVALID_OTP = 'INVALID_OTP',
  OTP_EXPIRED = 'OTP_EXPIRED',
  OTP_SESSION_LOCKED = 'OTP_SESSION_LOCKED',
  JOB_NOT_MODIFIABLE = 'JOB_NOT_MODIFIABLE',
  INVALID_WORKFLOW_STEP = 'INVALID_WORKFLOW_STEP',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
